name: Build and Push 
on:
  pull_request:
    branches:
      - 'master'
  release:
    types: [published]
jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: jdk11/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
          tags: |
            sitture/docker-gauge-java:latest
            sitture/docker-gauge-java:1.0.0
            ghcr.io/sitture/docker-gauge-java:latest
            ghcr.io/sitture/docker-gauge-java:1.0.0