name: Build Image 
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Set env variables
        run: |
          echo "GAUGE_LATEST_RELEASE=$$(curl --silent "https://api.github.com/repos/getgauge/gauge/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV
          echo "REPORTPORTAL_LATEST_RELEASE=$$(curl --silent "https://api.github.com/repos/reportportal/agent-net-gauge/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=sitture/docker-gauge-java
            name=ghcr.io/sitture/docker-gauge-java
          tags: |
            type=semver,pattern={{version}}
            type=sha
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            GAUGE_VERSION=${{ env.GAUGE_LATEST_RELEASE }}
            GAUGE_REPORTPORTAL_VERSION=${{ env.REPORTPORTAL_LATEST_RELEASE }}
          context: jdk11/
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}