name: openjdk-11
on:
  release:
    types: [published]
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    uses: ./.github/workflows/_build-template.yml
    with:
      directory: openjdk-11
      base_image_version: openjdk-11
      image_version: openjdk-11
    secrets: inherit
